# Generated by Django 4.2.11 on 2026-01-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='执行命令')),
                ('raw_output', models.TextField(verbose_name='原始输出')),
                ('parsed_result', models.JSONField(default=dict, verbose_name='解析结果')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('warning', '警告')], default='success', max_length=20, verbose_name='状态')),
                ('has_alert', models.BooleanField(default=False, verbose_name='是否告警')),
                ('alert_message', models.TextField(blank=True, null=True, verbose_name='告警信息')),
                ('inspection_time', models.DateTimeField(auto_now_add=True, verbose_name='巡检时间')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='是否定时任务')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录',
                'db_table': 'inspection_records',
                'ordering': ['-inspection_time'],
            },
        ),
    ]
