# Generated by Django 4.2.11 on 2026-01-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(max_length=200, verbose_name='SMTP服务器')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP端口')),
                ('smtp_username', models.CharField(max_length=200, verbose_name='SMTP用户名')),
                ('smtp_password_encrypted', models.TextField(verbose_name='SMTP密码(加密)')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='发件人邮箱')),
                ('sender_name', models.CharField(default='巡检系统', max_length=100, verbose_name='发件人名称')),
                ('use_tls', models.BooleanField(default=True, verbose_name='使用TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='使用SSL')),
                ('disk_threshold', models.PositiveIntegerField(default=80, verbose_name='磁盘告警阈值(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警配置',
                'verbose_name_plural': '告警配置',
                'db_table': 'alert_configs',
            },
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='收件人名称')),
                ('email', models.EmailField(max_length=254, verbose_name='收件人邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='alerts.alertconfig', verbose_name='告警配置')),
            ],
            options={
                'verbose_name': '告警收件人',
                'verbose_name_plural': '告警收件人',
                'db_table': 'alert_recipients',
            },
        ),
    ]
