# Generated by Django 4.2.11 on 2026-01-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='定时巡检', max_length=100, verbose_name='任务名称')),
                ('interval_type', models.CharField(choices=[('hourly', '每小时'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=20, verbose_name='周期类型')),
                ('interval_value', models.PositiveIntegerField(default=1, help_text='每隔多少个周期执行', verbose_name='周期值')),
                ('execute_time', models.TimeField(default='02:00:00', verbose_name='执行时间')),
                ('execute_day', models.PositiveIntegerField(default=1, help_text='周几(1-7)或每月几号(1-31)', verbose_name='执行日')),
                ('inspection_command', models.TextField(default='df -h', verbose_name='巡检命令')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '巡检调度',
                'verbose_name_plural': '巡检调度',
                'db_table': 'inspection_schedules',
            },
        ),
    ]
