# Generated by Django 4.2.11 on 2026-01-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务器名称')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.PositiveIntegerField(default=22, verbose_name='SSH端口')),
                ('ssh_username', models.CharField(max_length=100, verbose_name='SSH用户名')),
                ('ssh_password_encrypted', models.TextField(verbose_name='SSH密码(加密)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
                'db_table': 'servers',
                'ordering': ['-created_at'],
            },
        ),
    ]
